apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: curlimages/curl
        command:
            - "sleep"
            - "10"
            - "sh"
            - "-c"
            - |
              /bin/bash <<'EOF'
              curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Token ${GITHUB_ACCESS_TOKEN}" \
              -X POST \
              https://api.github.com/repos/eakman-nomad/argocd-example-apps/deployments \
              -d '{"ref":"master"}'
              EOF
      restartPolicy: Never
  backoffLimit: 0
